#define SHADING_MODE_COLOR 0
#define SHADING_MODE_DEPTH 1
#define SHADING_MODE_NORMAL 2
#define SHADING_MODE_NORMAL_SCREEN 3
#define SHADING_MODE_OPTICAL_FLOW_FORWARD 4
#define SHADING_MODE_OPTICAL_FLOW_BACKWARD 5